name: Security Audit & Build Test

on: [push]

jobs:
  audit-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install google-genai

      - name: Run AI Security Auditor
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        # Note the path: ai-auditor/script.py and app-cluster/Dockerfile
        run: python ai-auditor/ai_reviewer.py app-cluster/Dockerfile

      - name: Build Docker Image (Dry Run)
        working-directory: ./app-cluster
        run: docker compose build

   # NEW: The CD Deployment Job
  deploy:
    needs: audit-and-test # This ensures it ONLY deploys if the AI audit passes!
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST_IP }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Clone the repo if it's the first time, otherwise pull latest changes
            if [ ! -d "scalable-flask-cluster" ]; then
              git clone https://github.com/${{ github.repository }}.git
            fi
            cd scalable-flask-cluster/app-cluster
            git pull origin main
            
            # Spin up the High-Availability Cluster!
            docker compose up -d --build     
